// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/counter" | "/admin/counters" | "/admin/printers" | "/admin/reports" | "/admin/services" | "/admin/settings" | "/admin/users" | "/calling" | "/dashboard" | "/display/[counterId]" | "/login" | "/public/display" | "/public/display/[serviceId]" | "/public/display/counter-1" | "/public/display/counter-2" | "/public/display/counter-3" | "/public/display/counter-4" | "/public/display/counter/[counterId]" | "/service/[serviceId]" | "/staff" | "/staff/[counterId]" | "/staff/login" | "/waiting"
type AppRouteHandlerRoutes = "/api/call" | "/api/counters/[id]" | "/api/counters/[id]/services" | "/api/counters/[id]/services/[serviceId]" | "/api/counters/[id]/toggle-active" | "/api/queue" | "/api/services/[id]" | "/api/services/active" | "/api/ticket"
type PageRoutes = never
type LayoutRoutes = "/" | "/login" | "/staff"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/counter": {}
  "/admin/counters": {}
  "/admin/printers": {}
  "/admin/reports": {}
  "/admin/services": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/call": {}
  "/api/counters/[id]": { "id": string; }
  "/api/counters/[id]/services": { "id": string; }
  "/api/counters/[id]/services/[serviceId]": { "id": string; "serviceId": string; }
  "/api/counters/[id]/toggle-active": { "id": string; }
  "/api/queue": {}
  "/api/services/[id]": { "id": string; }
  "/api/services/active": {}
  "/api/ticket": {}
  "/calling": {}
  "/dashboard": {}
  "/display/[counterId]": { "counterId": string; }
  "/login": {}
  "/public/display": {}
  "/public/display/[serviceId]": { "serviceId": string; }
  "/public/display/counter-1": {}
  "/public/display/counter-2": {}
  "/public/display/counter-3": {}
  "/public/display/counter-4": {}
  "/public/display/counter/[counterId]": { "counterId": string; }
  "/service/[serviceId]": { "serviceId": string; }
  "/staff": {}
  "/staff/[counterId]": { "counterId": string; }
  "/staff/login": {}
  "/waiting": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/login": never
  "/staff": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
