// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(admin)/admin/counter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/counter">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/counter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/counters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/counters">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/counters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/printers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/printers">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/printers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/calling/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calling">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/calling/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/[serviceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display/[serviceId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/[serviceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/counter-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display/counter-1">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/counter-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/counter-2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display/counter-2">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/counter-2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/counter-3/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display/counter-3">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/counter-3/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/counter-4/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display/counter-4">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/counter-4/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/counter/[counterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display/counter/[counterId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/counter/[counterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/public/display/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/display">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/public/display/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/service/[serviceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service/[serviceId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/service/[serviceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/staff/[counterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/[counterId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/staff/[counterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/staff/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/staff/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/waiting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waiting">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/waiting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/display/[counterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/display/[counterId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/display/[counterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/call/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/call">> = Specific
  const handler = {} as typeof import("../../../src/app/api/call/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/counters/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/counters/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/counters/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/counters/[id]/services/[serviceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/counters/[id]/services/[serviceId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/counters/[id]/services/[serviceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/counters/[id]/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/counters/[id]/services">> = Specific
  const handler = {} as typeof import("../../../src/app/api/counters/[id]/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/counters/[id]/toggle-active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/counters/[id]/toggle-active">> = Specific
  const handler = {} as typeof import("../../../src/app/api/counters/[id]/toggle-active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/services/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/services/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/services/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/active">> = Specific
  const handler = {} as typeof import("../../../src/app/api/services/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ticket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ticket">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ticket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin)/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin)/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/staff/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/staff/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
