export const FONTAWESOME_ICONS = [
 { id: 1, class: "RiAccountCircleLine", name: "Account Circle" },
  { id: 2, class: "RiAccountPinCircleLine", name: "Account Pin" },
  { id: 3, class: "RiAddCircleLine", name: "Add Circle" },
  { id: 4, class: "RiAddLine", name: "Add" },
  { id: 5, class: "RiAlarmLine", name: "Alarm" },
  { id: 6, class: "RiAlertLine", name: "Alert" },
  { id: 7, class: "RiAppsLine", name: "Apps" },
  { id: 8, class: "RiArchiveLine", name: "Archive" },
  { id: 9, class: "RiArrowDownLine", name: "Arrow Down" },
  { id: 10, class: "RiArrowLeftLine", name: "Arrow Left" },

  { id: 11, class: "RiArrowRightLine", name: "Arrow Right" },
  { id: 12, class: "RiArrowUpLine", name: "Arrow Up" },
  { id: 13, class: "RiAttachmentLine", name: "Attachment" },
  { id: 14, class: "RiAwardLine", name: "Award" },
  { id: 15, class: "RiBarChartLine", name: "Bar Chart" },
  { id: 16, class: "RiBatteryLine", name: "Battery" },
  { id: 17, class: "RiBellLine", name: "Bell" },
  { id: 18, class: "RiBookmarkLine", name: "Bookmark" },
  { id: 19, class: "RiBriefcaseLine", name: "Briefcase" },
  { id: 20, class: "RiBuildingLine", name: "Building" },

  { id: 21, class: "RiBusLine", name: "Bus" },
  { id: 22, class: "RiCalculatorLine", name: "Calculator" },
  { id: 23, class: "RiCalendarLine", name: "Calendar" },
  { id: 24, class: "RiCameraLine", name: "Camera" },
  { id: 25, class: "RiCarLine", name: "Car" },
  { id: 26, class: "RiChat1Line", name: "Chat" },
  { id: 27, class: "RiCheckLine", name: "Check" },
  { id: 28, class: "RiCheckboxCircleLine", name: "Checkbox" },
  { id: 29, class: "RiClipboardLine", name: "Clipboard" },
  { id: 30, class: "RiCloseLine", name: "Close" },

  { id: 31, class: "RiCloudLine", name: "Cloud" },
  { id: 32, class: "RiCodeLine", name: "Code" },
  { id: 33, class: "RiCompassLine", name: "Compass" },
  { id: 34, class: "RiContactsLine", name: "Contacts" },
  { id: 35, class: "RiCouponLine", name: "Coupon" },
  { id: 36, class: "RiDashboardLine", name: "Dashboard" },
  { id: 37, class: "RiDatabaseLine", name: "Database" },
  { id: 38, class: "RiDeleteBinLine", name: "Delete" },
  { id: 39, class: "RiDeleteBin6Line", name: "Delete 2" },
  { id: 40, class: "RiDeviceLine", name: "Device" },

  { id: 41, class: "RiDownloadLine", name: "Download" },
  { id: 42, class: "RiEditLine", name: "Edit" },
  { id: 43, class: "RiEmotionLine", name: "Emotion" },
  { id: 44, class: "RiErrorWarningLine", name: "Warning" },
  { id: 45, class: "RiEyeLine", name: "Eye" },
  { id: 46, class: "RiEyeOffLine", name: "Eye Off" },
  { id: 47, class: "RiFileLine", name: "File" },
  { id: 48, class: "RiFileCopyLine", name: "Copy" },
  { id: 49, class: "RiFileDownloadLine", name: "File Download" },
  { id: 50, class: "RiFileUploadLine", name: "File Upload" },

  { id: 51, class: "RiFilterLine", name: "Filter" },
  { id: 52, class: "RiFlagLine", name: "Flag" },
  { id: 53, class: "RiFolderLine", name: "Folder" },
  { id: 54, class: "RiFolderOpenLine", name: "Folder Open" },
  { id: 55, class: "RiFullscreenLine", name: "Fullscreen" },
  { id: 56, class: "RiGamepadLine", name: "Gamepad" },
  { id: 57, class: "RiGiftLine", name: "Gift" },
  { id: 58, class: "RiGlobalLine", name: "Global" },
  { id: 59, class: "RiGpsLine", name: "GPS" },
  { id: 60, class: "RiGroupLine", name: "Group" },

  { id: 61, class: "RiHandLine", name: "Hand" },
  { id: 62, class: "RiHardDriveLine", name: "Hard Drive" },
  { id: 63, class: "RiHeadphoneLine", name: "Headphone" },
  { id: 64, class: "RiHeartLine", name: "Heart" },
  { id: 65, class: "RiHomeLine", name: "Home" },
  { id: 66, class: "RiImageLine", name: "Image" },
  { id: 67, class: "RiInboxLine", name: "Inbox" },
  { id: 68, class: "RiInformationLine", name: "Info" },
  { id: 69, class: "RiKeyLine", name: "Key" },
  { id: 70, class: "RiLightbulbLine", name: "Idea" },

  { id: 71, class: "RiLinkLine", name: "Link" },
  { id: 72, class: "RiListCheckLine", name: "Checklist" },
  { id: 73, class: "RiLoaderLine", name: "Loading" },
  { id: 74, class: "RiLockLine", name: "Lock" },
  { id: 75, class: "RiLoginBoxLine", name: "Login" },
  { id: 76, class: "RiLogoutBoxLine", name: "Logout" },
  { id: 77, class: "RiMailLine", name: "Mail" },
  { id: 78, class: "RiMapLine", name: "Map" },
  { id: 79, class: "RiMapPinLine", name: "Location" },
  { id: 80, class: "RiMenuLine", name: "Menu" },

  { id: 81, class: "RiMessageLine", name: "Message" },
  { id: 82, class: "RiMicLine", name: "Mic" },
  { id: 83, class: "RiMoneyDollarCircleLine", name: "Money" },
  { id: 84, class: "RiMoonLine", name: "Moon" },
  { id: 85, class: "RiMoreLine", name: "More" },
  { id: 86, class: "RiNavigationLine", name: "Navigation" },
  { id: 87, class: "RiNotificationLine", name: "Notification" },
  { id: 88, class: "RiPaletteLine", name: "Palette" },
  { id: 89, class: "RiPauseLine", name: "Pause" },
  { id: 90, class: "RiPenNibLine", name: "Pen" },

  { id: 91, class: "RiPhoneLine", name: "Phone" },
  { id: 92, class: "RiPlayLine", name: "Play" },
  { id: 93, class: "RiPrinterLine", name: "Printer" },
  { id: 94, class: "RiRefreshLine", name: "Refresh" },
  { id: 95, class: "RiRepeatLine", name: "Repeat" },
  { id: 96, class: "RiRoadMapLine", name: "Roadmap" },
  { id: 97, class: "RiRocketLine", name: "Rocket" },
  { id: 98, class: "RiSaveLine", name: "Save" },
  { id: 99, class: "RiSearchLine", name: "Search" },
  { id: 100, class: "RiSendPlaneLine", name: "Send" },
  { id: 101, class: "RiShieldLine", name: "Shield" },
{ id: 102, class: "RiShoppingBagLine", name: "Shopping Bag" },
{ id: 103, class: "RiShoppingCartLine", name: "Shopping Cart" },
{ id: 104, class: "RiShuffleLine", name: "Shuffle" },
{ id: 105, class: "RiSignalWifiLine", name: "Wifi Signal" },
{ id: 106, class: "RiSmartphoneLine", name: "Smartphone" },
{ id: 107, class: "RiSoundModuleLine", name: "Sound" },
{ id: 108, class: "RiSpamLine", name: "Spam" },
{ id: 109, class: "RiSpeakerLine", name: "Speaker" },
{ id: 110, class: "RiSpeedLine", name: "Speed" },

{ id: 111, class: "RiStackLine", name: "Stack" },
{ id: 112, class: "RiStarLine", name: "Star" },
{ id: 113, class: "RiStopLine", name: "Stop" },
{ id: 114, class: "RiStoreLine", name: "Store" },
{ id: 115, class: "RiSuitcaseLine", name: "Suitcase" },
{ id: 116, class: "RiSunLine", name: "Sun" },
{ id: 117, class: "RiTableLine", name: "Table" },
{ id: 118, class: "RiTabletLine", name: "Tablet" },
{ id: 119, class: "RiTagLine", name: "Tag" },
{ id: 120, class: "RiTaskLine", name: "Task" },

{ id: 121, class: "RiTerminalLine", name: "Terminal" },
{ id: 122, class: "RiThumbUpLine", name: "Thumb Up" },
{ id: 123, class: "RiThumbDownLine", name: "Thumb Down" },
{ id: 124, class: "RiTimeLine", name: "Time" },
{ id: 125, class: "RiTimerLine", name: "Timer" },
{ id: 126, class: "RiToolsLine", name: "Tools" },
{ id: 127, class: "RiTranslateLine", name: "Translate" },
{ id: 128, class: "RiTruckLine", name: "Truck" },
{ id: 129, class: "RiTrophyLine", name: "Trophy" },
{ id: 130, class: "RiTvLine", name: "TV" },

{ id: 131, class: "RiUploadCloudLine", name: "Upload Cloud" },
{ id: 132, class: "RiUsbLine", name: "USB" },
{ id: 133, class: "RiUserAddLine", name: "User Add" },
{ id: 134, class: "RiUserFollowLine", name: "User Follow" },
{ id: 135, class: "RiUserHeartLine", name: "User Heart" },
{ id: 136, class: "RiUserSettingsLine", name: "User Settings" },
{ id: 137, class: "RiUserStarLine", name: "User Star" },
{ id: 138, class: "RiUserUnfollowLine", name: "User Unfollow" },
{ id: 139, class: "RiVideoAddLine", name: "Video Add" },
{ id: 140, class: "RiVideoDownloadLine", name: "Video Download" },

{ id: 141, class: "RiVideoUploadLine", name: "Video Upload" },
{ id: 142, class: "RiVipLine", name: "VIP" },
{ id: 143, class: "RiVolumeDownLine", name: "Volume Down" },
{ id: 144, class: "RiVolumeMuteLine", name: "Volume Mute" },
{ id: 145, class: "RiVolumeUpLine", name: "Volume Up" },
{ id: 146, class: "RiWalletLine", name: "Wallet" },
{ id: 147, class: "RiWifiLine", name: "Wifi" },
{ id: 148, class: "RiWifiOffLine", name: "Wifi Off" },
{ id: 149, class: "RiWindowLine", name: "Window" },
{ id: 150, class: "RiZoomInLine", name: "Zoom In" },

{ id: 151, class: "RiZoomOutLine", name: "Zoom Out" },
{ id: 152, class: "RiBookLine", name: "Book" },
{ id: 153, class: "RiBookOpenLine", name: "Book Open" },
{ id: 154, class: "RiBookMarkLine", name: "Bookmark 2" },
{ id: 155, class: "RiContactsBookLine", name: "Contacts Book" },
{ id: 156, class: "RiFileListLine", name: "File List" },
{ id: 157, class: "RiFilePaperLine", name: "File Paper" },
{ id: 158, class: "RiFileWarningLine", name: "File Warning" },
{ id: 159, class: "RiFileShieldLine", name: "File Shield" },
{ id: 160, class: "RiFileSettingsLine", name: "File Settings" },

{ id: 161, class: "RiFolderAddLine", name: "Folder Add" },
{ id: 162, class: "RiFolderDownloadLine", name: "Folder Download" },
{ id: 163, class: "RiFolderUploadLine", name: "Folder Upload" },
{ id: 164, class: "RiFolderSharedLine", name: "Folder Shared" },
{ id: 165, class: "RiFolderReceivedLine", name: "Folder Received" },
{ id: 166, class: "RiFolderReduceLine", name: "Folder Reduce" },
{ id: 167, class: "RiFolderTransferLine", name: "Folder Transfer" },
{ id: 168, class: "RiFolderWarningLine", name: "Folder Warning" },
{ id: 169, class: "RiFolderShieldLine", name: "Folder Shield" },
{ id: 170, class: "RiFolderSettingsLine", name: "Folder Settings" },

{ id: 171, class: "RiCloudOffLine", name: "Cloud Off" },
{ id: 172, class: "RiCloudWindyLine", name: "Cloud Windy" },
{ id: 173, class: "RiCloudyLine", name: "Cloudy" },
{ id: 174, class: "RiThunderstormsLine", name: "Thunderstorm" },
{ id: 175, class: "RiSnowyLine", name: "Snow" },
{ id: 176, class: "RiMistLine", name: "Mist" },
{ id: 177, class: "RiTempColdLine", name: "Cold" },
{ id: 178, class: "RiTempHotLine", name: "Hot" },
{ id: 179, class: "RiCelsiusLine", name: "Celsius" },
{ id: 180, class: "RiFahrenheitLine", name: "Fahrenheit" },

{ id: 181, class: "RiHospitalLine", name: "Hospital" },
{ id: 182, class: "RiMedicineBottleLine", name: "Medicine" },
{ id: 183, class: "RiFirstAidKitLine", name: "First Aid" },
{ id: 184, class: "RiMentalHealthLine", name: "Mental Health" },
{ id: 185, class: "RiStethoscopeLine", name: "Stethoscope" },
{ id: 186, class: "RiSurgicalMaskLine", name: "Mask" },
{ id: 187, class: "RiPulseLine", name: "Pulse" },
{ id: 188, class: "RiHeartPulseLine", name: "Heart Pulse" },
{ id: 189, class: "RiTestTubeLine", name: "Test Tube" },
{ id: 190, class: "RiVirusLine", name: "Virus" },

{ id: 191, class: "RiGovernmentLine", name: "Government" },
{ id: 192, class: "RiBuilding2Line", name: "Building 2" },
{ id: 193, class: "RiBankLine", name: "Bank" },
{ id: 194, class: "RiAuctionLine", name: "Auction" },
// { id: 195, class: "RiFileLawLine", name: "Law File" },
{ id: 196, class: "RiScalesLine", name: "Scales" },
// { id: 197, class: "RiStampLine", name: "Stamp" },
{ id: 198, class: "RiClipboardLine", name: "Clipboard 2" },
{ id: 199, class: "RiDraftLine", name: "Draft" },
{ id: 200, class: "RiArticleLine", name: "Article" }
];